---
- name: Verify Docker Installation
  hosts: all_servers
  gather_facts: no
  tasks:
    - name: Check Docker status and versions
      raw: |
        echo "🔍 DOCKER VERIFICATION REPORT"
        echo "============================="
        echo "Server: $(hostname)"
        echo "OS: $(cat /etc/os-release | grep PRETTY_NAME | cut -d'\"' -f2)"
        echo "User: $(whoami)"
        echo ""

        # Check Docker
        if command -v docker &> /dev/null; then
          DOCKER_VERSION=$(docker --version)
          echo "✅ Docker: $DOCKER_VERSION"
          
          # Check Docker service
          if sudo systemctl is-active --quiet docker; then
            echo "✅ Docker service: Running"
          else
            echo "❌ Docker service: Not running"
          fi
          
          # Check user in docker group
          if groups | grep -q docker; then
            echo "✅ User in docker group: Yes"
          else
            echo "⚠️  User in docker group: No (need re-login)"
          fi
        else
          echo "❌ Docker: Not installed"
        fi

        # Check Docker Compose
        if command -v docker &> /dev/null && docker compose version &> /dev/null; then
          COMPOSE_VERSION=$(docker compose version --short)
          echo "✅ Docker Compose: v$COMPOSE_VERSION"
        elif command -v docker-compose &> /dev/null; then
          COMPOSE_VERSION=$(docker-compose --version)
          echo "✅ Docker Compose: $COMPOSE_VERSION"
        else
          echo "❌ Docker Compose: Not available"
        fi

        echo ""
        echo "============================="
      register: verification_result

    - name: Display verification results
      debug:
        var: verification_result.stdout_lines

- name: Summary Report
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Final summary
      debug:
        msg: |
          🏁 VERIFICATION COMPLETE
          =======================
          Check the output above for each server status.

          If Docker is installed but user group shows "No":
          1. Log out from each server
          2. Log back in 
          3. Run this verification again
