---
- name: Deploy Node Exporter on Monitoring Agents
  hosts: monitoring_agents
  become: yes
  gather_facts: yes
  vars:
    node_exporter_version: "1.7.0"
    node_exporter_user: "node_exporter"
    node_exporter_port: 9100
    
  tasks:
    - name: Create node_exporter user
      user:
        name: "{{ node_exporter_user }}"
        system: yes
        shell: /bin/false
        home: /var/lib/node_exporter
        createhome: no
        
    - name: Create node_exporter directories
      file:
        path: "{{ item }}"
        state: directory
        owner: "{{ node_exporter_user }}"
        group: "{{ node_exporter_user }}"
        mode: '0755'
      loop:
        - /etc/node_exporter
        - /var/lib/node_exporter
        
    - name: Download and install Node Exporter (Amazon Linux)
      raw: |
        cd /tmp
        curl -LO https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz
        tar -xvf node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz
        sudo cp node_exporter-{{ node_exporter_version }}.linux-amd64/node_exporter /usr/local/bin/
        sudo chown {{ node_exporter_user }}:{{ node_exporter_user }} /usr/local/bin/node_exporter
        sudo chmod +x /usr/local/bin/node_exporter
        rm -rf node_exporter-{{ node_exporter_version }}.linux-amd64*
      when: ansible_distribution == "Amazon" and install_node_exporter | default(false)
      
    - name: Install Node Exporter via package manager (Ubuntu)
      apt:
        name: prometheus-node-exporter
        state: present
      when: ansible_distribution == "Ubuntu" and install_node_exporter | default(false)
      
    - name: Create systemd service file for Node Exporter (Amazon Linux)
      copy:
        content: |
          [Unit]
          Description=Node Exporter
          Wants=network-online.target
          After=network-online.target

          [Service]
          User={{ node_exporter_user }}
          Group={{ node_exporter_user }}
          Type=simple
          ExecStart=/usr/local/bin/node_exporter \
            --web.listen-address=:{{ node_exporter_port }} \
            --path.procfs=/proc \
            --path.sysfs=/sys \
            --collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)

          [Install]
          WantedBy=multi-user.target
        dest: /etc/systemd/system/node_exporter.service
        owner: root
        group: root
        mode: '0644'
      when: ansible_distribution == "Amazon" and install_node_exporter | default(false)
      
    - name: Reload systemd and start Node Exporter
      systemd:
        daemon_reload: yes
        name: node_exporter
        state: started
        enabled: yes
      when: install_node_exporter | default(false)
      
    - name: Wait for Node Exporter to be ready
      wait_for:
        port: "{{ node_exporter_port }}"
        host: "{{ ansible_default_ipv4.address }}"
        delay: 5
        timeout: 30
      when: install_node_exporter | default(false)
      
    - name: Verify Node Exporter installation
      raw: curl -s http://localhost:{{ node_exporter_port }}/metrics | head -5
      register: node_exporter_check
      when: install_node_exporter | default(false)
      
    - name: Display Node Exporter status
      debug:
        msg: |
          🎉 NODE EXPORTER DEPLOYED SUCCESSFULLY!
          =====================================
          
          📊 Access URL:
          - Node Exporter: http://{{ ansible_default_ipv4.address }}:{{ node_exporter_port }}/metrics
          
          📋 Service Status:
          ✅ Node Exporter: Running on port {{ node_exporter_port }}
          
          🔍 Metrics Preview:
          {{ node_exporter_check.stdout_lines[:5] | join('\n') }}
      when: install_node_exporter | default(false)